-- UPDATED SCHEMA: Base schema + all migrations applied
-- Generated by merging schema.sql with all migration files
-- Includes all changes through Phase 3/Phase 4

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ==========================================
-- CORE USERS & ROLES
-- ==========================================
CREATE TABLE IF NOT EXISTS users (
  id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
  role TEXT NOT NULL CHECK (role IN ('user', 'vendor', 'admin')) DEFAULT 'user',
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  campus_id TEXT,
  wallet_balance NUMERIC(10, 2) NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Ensure wallet_balance column exists on existing users table
ALTER TABLE IF EXISTS public.users ADD COLUMN IF NOT EXISTS wallet_balance NUMERIC(10, 2) NOT NULL DEFAULT 0;

-- ==========================================
-- VENDORS & DELIVERY INFRASTRUCTURE
-- ==========================================
CREATE TABLE IF NOT EXISTS vendors (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  owner_id UUID REFERENCES public.users(id) NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  is_open BOOLEAN DEFAULT true,
  image_url TEXT,
  status TEXT NOT NULL CHECK (status IN ('pending', 'approved', 'rejected')) DEFAULT 'pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS campus_buildings (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  code TEXT,
  name TEXT NOT NULL,
  address TEXT,
  latitude DECIMAL(10,7),
  longitude DECIMAL(10,7),
  delivery_notes TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS delivery_zones (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  name TEXT NOT NULL,
  building_id UUID REFERENCES public.campus_buildings(id) ON DELETE SET NULL,
  geojson JSONB,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS class_sessions (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
  building_id UUID REFERENCES public.campus_buildings(id) ON DELETE SET NULL,
  room TEXT,
  course_label TEXT,
  starts_at TIMESTAMP WITH TIME ZONE,
  ends_at TIMESTAMP WITH TIME ZONE,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- MENU & MENU ITEMS
-- ==========================================
CREATE TABLE IF NOT EXISTS menus (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  vendor_id UUID REFERENCES public.vendors(id) ON DELETE CASCADE,
  category_name TEXT NOT NULL,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Ensure timestamps exist on existing menus table
ALTER TABLE IF EXISTS public.menus ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now());
ALTER TABLE IF EXISTS public.menus ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now());

CREATE TABLE IF NOT EXISTS menu_items (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  menu_id UUID REFERENCES public.menus(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT,
  price DECIMAL(10,2) NOT NULL,
  is_available BOOLEAN DEFAULT true,
  image_url TEXT,
  storage_path TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Ensure columns exist on existing menu_items table
ALTER TABLE IF EXISTS public.menu_items ADD COLUMN IF NOT EXISTS storage_path TEXT;
ALTER TABLE IF EXISTS public.menu_items ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now());
ALTER TABLE IF EXISTS public.menu_items ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now());

-- ==========================================
-- MEDIA TRACKING
-- ==========================================
CREATE TABLE IF NOT EXISTS media_items (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  vendor_id UUID REFERENCES public.vendors(id) ON DELETE CASCADE NOT NULL,
  file_name TEXT NOT NULL,
  file_path TEXT NOT NULL UNIQUE,
  file_size_bytes BIGINT NOT NULL,
  mime_type TEXT NOT NULL,
  storage_url TEXT NOT NULL,
  entity_type TEXT NOT NULL CHECK (entity_type IN ('menu_item', 'vendor_profile', 'order_proof')),
  entity_id UUID,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_media_items_vendor_id ON media_items(vendor_id);
CREATE INDEX IF NOT EXISTS idx_media_items_entity ON media_items(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_media_items_active ON media_items(is_active) WHERE is_active = true;

-- ==========================================
-- PROMOTIONS
-- ==========================================
CREATE TABLE IF NOT EXISTS promotions (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  description TEXT,
  discount_type TEXT NOT NULL CHECK (discount_type IN ('percent', 'fixed')),
  discount_value DECIMAL(10,2) NOT NULL,
  min_order_amount DECIMAL(10,2) DEFAULT 0,
  max_discount_amount DECIMAL(10,2),
  starts_at TIMESTAMP WITH TIME ZONE,
  ends_at TIMESTAMP WITH TIME ZONE,
  is_active BOOLEAN DEFAULT true,
  usage_limit INTEGER,
  usage_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- ORDERS & FULFILLMENT
-- ==========================================
CREATE TABLE IF NOT EXISTS orders (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id UUID REFERENCES public.users(id) NOT NULL,
  vendor_id UUID REFERENCES public.vendors(id) NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('pending', 'accepted', 'preparing', 'ready', 'completed', 'cancelled')) DEFAULT 'pending',
  delivery_mode TEXT NOT NULL CHECK (delivery_mode IN ('standard', 'class')) DEFAULT 'standard',
  delivery_instructions TEXT,
  delivery_location_label TEXT,
  delivery_building_id UUID REFERENCES public.campus_buildings(id) ON DELETE SET NULL,
  delivery_room TEXT,
  delivery_zone_id UUID REFERENCES public.delivery_zones(id) ON DELETE SET NULL,
  quiet_mode BOOLEAN DEFAULT false,
  handoff_code TEXT,
  handoff_status TEXT NOT NULL CHECK (handoff_status IN ('pending', 'arrived_building', 'arrived_class', 'delivered', 'failed')) DEFAULT 'pending',
  handoff_proof_url TEXT,
  class_start_at TIMESTAMP WITH TIME ZONE,
  class_end_at TIMESTAMP WITH TIME ZONE,
  scheduled_for TIMESTAMP WITH TIME ZONE,
  total_amount DECIMAL(10,2) NOT NULL,
  discount_amount DECIMAL(10,2) DEFAULT 0,
  promo_id UUID REFERENCES public.promotions(id),
  promo_code TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS order_delivery_locations (
  order_id UUID REFERENCES public.orders(id) ON DELETE CASCADE PRIMARY KEY,
  lat DECIMAL(10,7) NOT NULL,
  lng DECIMAL(10,7) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS order_items (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  order_id UUID REFERENCES public.orders(id) ON DELETE CASCADE,
  item_id UUID REFERENCES public.menu_items(id),
  quantity INTEGER NOT NULL,
  unit_price DECIMAL(10,2) NOT NULL,
  special_instructions TEXT
);

CREATE TABLE IF NOT EXISTS payments (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  order_id UUID REFERENCES public.orders(id) ON DELETE CASCADE,
  amount DECIMAL(10,2) NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('pending', 'successful', 'failed')) DEFAULT 'pending',
  provider_ref TEXT
);

-- ==========================================
-- GROUP ORDERS & REFUNDS
-- ==========================================
CREATE TABLE IF NOT EXISTS group_orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id UUID REFERENCES public.orders(id) ON DELETE CASCADE NOT NULL UNIQUE,
  host_user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'completed', 'cancelled')),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS group_order_members (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  group_order_id UUID REFERENCES public.group_orders(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  contribution_amount NUMERIC(10, 2) NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(group_order_id, user_id)
);

CREATE TABLE IF NOT EXISTS refund_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id UUID REFERENCES public.orders(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  reason TEXT NOT NULL,
  amount NUMERIC(10, 2) NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'processed')),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- WALLET & TRANSACTIONS
-- ==========================================
CREATE TABLE IF NOT EXISTS wallet_transactions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  amount NUMERIC(10, 2) NOT NULL,
  transaction_type TEXT NOT NULL CHECK (transaction_type IN ('topup', 'debit', 'credit', 'refund')),
  status TEXT NOT NULL DEFAULT 'completed' CHECK (status IN ('pending', 'completed', 'failed')),
  source TEXT,
  reference TEXT,
  idempotency_key TEXT,
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Ensure column exists on existing tables
ALTER TABLE IF EXISTS public.wallet_transactions ADD COLUMN IF NOT EXISTS idempotency_key TEXT;
ALTER TABLE IF EXISTS public.wallet_transactions ADD COLUMN IF NOT EXISTS source TEXT;
ALTER TABLE IF EXISTS public.wallet_transactions ADD COLUMN IF NOT EXISTS reference TEXT;
ALTER TABLE IF EXISTS public.wallet_transactions ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}'::jsonb;

CREATE INDEX IF NOT EXISTS wallet_transactions_user_id_created_at_idx
  ON public.wallet_transactions (user_id, created_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS wallet_transactions_user_id_idempotency_idx
  ON public.wallet_transactions (user_id, idempotency_key)
  WHERE idempotency_key IS NOT NULL;

-- ==========================================
-- PROMOTIONS & LOYALTY
-- ==========================================
CREATE TABLE IF NOT EXISTS promotion_redemptions (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  promo_id UUID REFERENCES public.promotions(id) ON DELETE CASCADE,
  user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
  order_id UUID REFERENCES public.orders(id) ON DELETE SET NULL,
  redeemed_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS referral_codes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  code TEXT NOT NULL UNIQUE,
  is_active BOOLEAN NOT NULL DEFAULT true,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS referral_redemptions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  referral_code_id UUID REFERENCES public.referral_codes(id) ON DELETE CASCADE NOT NULL,
  referee_user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(referral_code_id, referee_user_id)
);

CREATE TABLE IF NOT EXISTS loyalty_accounts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL UNIQUE,
  points INTEGER NOT NULL DEFAULT 0,
  tier TEXT NOT NULL DEFAULT 'bronze' CHECK (tier IN ('bronze', 'silver', 'gold', 'platinum')),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS loyalty_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  points_delta INTEGER NOT NULL,
  reason TEXT NOT NULL,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- SUBSCRIPTIONS & WATCHES
-- ==========================================
CREATE TABLE IF NOT EXISTS subscriptions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  plan TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'paused', 'cancelled')),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS vendor_watches (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  vendor_id UUID REFERENCES public.vendors(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, vendor_id)
);

-- ==========================================
-- REVIEWS & FEEDBACK
-- ==========================================
CREATE TABLE IF NOT EXISTS reviews (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  order_id UUID REFERENCES public.orders(id) ON DELETE CASCADE,
  vendor_id UUID REFERENCES public.vendors(id) ON DELETE CASCADE,
  user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
  rating INTEGER CHECK (rating >= 1 AND rating <= 5) NOT NULL,
  comment TEXT
);

-- ==========================================
-- NOTIFICATIONS & DEVICE TOKENS
-- ==========================================
CREATE TABLE IF NOT EXISTS notifications (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
  audience TEXT NOT NULL CHECK (audience IN ('user', 'vendor', 'admin')) DEFAULT 'user',
  type TEXT DEFAULT 'general',
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  metadata JSONB,
  is_read BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS device_tokens (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
  audience TEXT NOT NULL CHECK (audience IN ('user', 'vendor', 'admin')) DEFAULT 'user',
  token TEXT NOT NULL,
  platform TEXT NOT NULL CHECK (platform IN ('ios', 'android', 'web', 'unknown')) DEFAULT 'unknown',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, token)
);

-- ==========================================
-- FAVORITES & CARTS
-- ==========================================
CREATE TABLE IF NOT EXISTS favorites (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
  vendor_id UUID REFERENCES public.vendors(id) ON DELETE CASCADE,
  UNIQUE(user_id, vendor_id)
);

CREATE TABLE IF NOT EXISTS user_carts (
  user_id UUID REFERENCES public.users(id) ON DELETE CASCADE PRIMARY KEY,
  items JSONB NOT NULL DEFAULT '[]'::jsonb,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- VENDOR SETTINGS & STAFF MANAGEMENT
-- ==========================================
CREATE TABLE IF NOT EXISTS vendor_settings (
  vendor_id UUID REFERENCES public.vendors(id) ON DELETE CASCADE PRIMARY KEY,
  preparation_time_avg INTEGER DEFAULT 15,
  auto_accept_orders BOOLEAN DEFAULT false,
  busy_mode_enabled BOOLEAN DEFAULT false,
  busy_mode_message TEXT,
  holiday_until TIMESTAMP WITH TIME ZONE,
  preferred_language TEXT DEFAULT 'English',
  theme_dark_mode BOOLEAN DEFAULT false,
  theme_high_contrast BOOLEAN DEFAULT false,
  app_compact_cards BOOLEAN DEFAULT false,
  app_silent_alerts BOOLEAN DEFAULT false,
  app_notification_enabled BOOLEAN DEFAULT true,
  app_auto_print_receipts BOOLEAN DEFAULT false
);

-- Ensure all preference columns exist on existing vendor_settings table
ALTER TABLE IF EXISTS public.vendor_settings ADD COLUMN IF NOT EXISTS busy_mode_enabled BOOLEAN DEFAULT false;
ALTER TABLE IF EXISTS public.vendor_settings ADD COLUMN IF NOT EXISTS busy_mode_message TEXT;
ALTER TABLE IF EXISTS public.vendor_settings ADD COLUMN IF NOT EXISTS holiday_until TIMESTAMP WITH TIME ZONE;
ALTER TABLE IF EXISTS public.vendor_settings ADD COLUMN IF NOT EXISTS preferred_language TEXT DEFAULT 'English';
ALTER TABLE IF EXISTS public.vendor_settings ADD COLUMN IF NOT EXISTS theme_dark_mode BOOLEAN DEFAULT false;
ALTER TABLE IF EXISTS public.vendor_settings ADD COLUMN IF NOT EXISTS theme_high_contrast BOOLEAN DEFAULT false;
ALTER TABLE IF EXISTS public.vendor_settings ADD COLUMN IF NOT EXISTS app_compact_cards BOOLEAN DEFAULT false;
ALTER TABLE IF EXISTS public.vendor_settings ADD COLUMN IF NOT EXISTS app_silent_alerts BOOLEAN DEFAULT false;
ALTER TABLE IF EXISTS public.vendor_settings ADD COLUMN IF NOT EXISTS app_notification_enabled BOOLEAN DEFAULT true;
ALTER TABLE IF EXISTS public.vendor_settings ADD COLUMN IF NOT EXISTS app_auto_print_receipts BOOLEAN DEFAULT false;

CREATE TABLE IF NOT EXISTS vendor_staff_members (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  vendor_id UUID REFERENCES public.vendors(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  role_key TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'suspended')),
  email TEXT,
  phone TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(vendor_id, user_id)
);

CREATE TABLE IF NOT EXISTS vendor_staff_roles (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  vendor_id UUID REFERENCES public.vendors(id) ON DELETE CASCADE NOT NULL,
  role_key TEXT NOT NULL,
  permissions JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(vendor_id, role_key)
);

CREATE TABLE IF NOT EXISTS vendor_staff_invitations (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  vendor_id UUID REFERENCES public.vendors(id) ON DELETE CASCADE NOT NULL,
  invited_by UUID REFERENCES public.users(id) ON DELETE SET NULL,
  invited_user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
  email TEXT NOT NULL,
  role_key TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'revoked', 'expired')),
  invite_token TEXT NOT NULL UNIQUE,
  expires_at TIMESTAMP WITH TIME ZONE,
  accepted_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- CHAT & SUPPORT SYSTEM
-- ==========================================
CREATE TABLE IF NOT EXISTS chat_rooms (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  type TEXT CHECK (type IN ('user-vendor', 'user-delivery', 'support', 'group')),
  topic TEXT,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'closed')),
  created_by UUID REFERENCES public.users(id) ON DELETE SET NULL,
  order_id UUID NULL,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

-- Ensure new columns exist on existing chat_rooms table
ALTER TABLE IF EXISTS public.chat_rooms ADD COLUMN IF NOT EXISTS topic TEXT;
ALTER TABLE IF EXISTS public.chat_rooms ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'closed'));
ALTER TABLE IF EXISTS public.chat_rooms ADD COLUMN IF NOT EXISTS created_by UUID REFERENCES public.users(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS chat_room_participants (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  room_id UUID REFERENCES chat_rooms(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
  vendor_id UUID,
  delivery_agent_id UUID,
  admin_id UUID,
  joined_at TIMESTAMP DEFAULT now(),
  UNIQUE(room_id, user_id, vendor_id, delivery_agent_id, admin_id)
);

CREATE INDEX IF NOT EXISTS chat_room_participants_room_user_idx
  ON public.chat_room_participants (room_id, user_id);

CREATE TABLE IF NOT EXISTS chat_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  room_id UUID REFERENCES chat_rooms(id) ON DELETE CASCADE,
  sender_type TEXT CHECK (sender_type IN ('user', 'vendor', 'delivery', 'admin')),
  sender_id UUID,
  message TEXT,
  sent_at TIMESTAMP DEFAULT now(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  is_read BOOLEAN DEFAULT FALSE
);

-- Ensure created_at column exists on existing chat_messages table
ALTER TABLE IF EXISTS public.chat_messages ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now());

CREATE INDEX IF NOT EXISTS chat_messages_room_sent_at_idx
  ON public.chat_messages (room_id, sent_at DESC);

-- ==========================================
-- SUPPORT & TICKETING
-- ==========================================
CREATE TABLE IF NOT EXISTS support_tickets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id UUID REFERENCES public.orders(id) ON DELETE SET NULL,
  user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'in_progress', 'resolved', 'closed')),
  priority TEXT NOT NULL DEFAULT 'normal' CHECK (priority IN ('low', 'normal', 'high', 'urgent')),
  assignee_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
  resolution_note TEXT,
  subject TEXT,
  description TEXT,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

-- Ensure new columns exist on existing support_tickets table
ALTER TABLE IF EXISTS public.support_tickets ADD COLUMN IF NOT EXISTS priority TEXT NOT NULL DEFAULT 'normal' CHECK (priority IN ('low', 'normal', 'high', 'urgent'));
ALTER TABLE IF EXISTS public.support_tickets ADD COLUMN IF NOT EXISTS assignee_id UUID REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE IF EXISTS public.support_tickets ADD COLUMN IF NOT EXISTS resolution_note TEXT;
ALTER TABLE IF EXISTS public.support_tickets ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES public.users(id) ON DELETE CASCADE;
ALTER TABLE IF EXISTS public.support_tickets ADD COLUMN IF NOT EXISTS order_id UUID REFERENCES public.orders(id) ON DELETE SET NULL;
ALTER TABLE IF EXISTS public.support_tickets ALTER COLUMN status SET DEFAULT 'open';

CREATE INDEX IF NOT EXISTS support_tickets_user_id_updated_at_idx
  ON public.support_tickets (user_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS support_ticket_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id UUID REFERENCES public.support_tickets(id) ON DELETE CASCADE NOT NULL,
  actor_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
  actor_role TEXT,
  event_type TEXT NOT NULL,
  event_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS support_ticket_events_ticket_created_idx
  ON public.support_ticket_events (ticket_id, created_at DESC);

-- ==========================================
-- ACCOUNT MANAGEMENT & DELETION
-- ==========================================
CREATE TABLE IF NOT EXISTS user_deletion_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL UNIQUE,
  status TEXT NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'cancelled', 'completed')),
  requested_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  delete_after TIMESTAMP WITH TIME ZONE NOT NULL,
  cancelled_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS user_deletion_requests_user_id_idx
  ON public.user_deletion_requests (user_id);

-- ==========================================
-- ADMIN AUDIT LOGS
-- ==========================================
CREATE TABLE IF NOT EXISTS admin_logs (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  admin_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
  action_performed TEXT NOT NULL,
  target_id UUID,
  reason TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- PASSWORD RESET OTP
-- ==========================================
CREATE TABLE IF NOT EXISTS password_reset_codes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  email TEXT NOT NULL,
  code_hash TEXT NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 0,
  consumed_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS password_reset_codes_email_created_idx
  ON public.password_reset_codes (email, created_at DESC);

CREATE INDEX IF NOT EXISTS password_reset_codes_user_created_idx
  ON public.password_reset_codes (user_id, created_at DESC);

-- ==========================================
-- RLS POLICIES
-- ==========================================

-- Enable RLS on all tables
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vendors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menus ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_delivery_locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.promotions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.promotion_redemptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.device_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.favorites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_carts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vendor_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vendor_staff_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vendor_staff_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vendor_staff_invitations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campus_buildings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.delivery_zones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.class_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.media_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wallet_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.referral_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.referral_redemptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.loyalty_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.loyalty_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vendor_watches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.group_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.group_order_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.refund_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_deletion_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_room_participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_ticket_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.password_reset_codes ENABLE ROW LEVEL SECURITY;

-- Drop existing policies to avoid conflicts
DO $$ DECLARE
    r RECORD;
BEGIN
    FOR r IN (SELECT policyname, tablename FROM pg_policies WHERE schemaname = 'public') LOOP
        EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', r.policyname, r.tablename);
    END LOOP;
END $$;

-- ==========================================
-- USER POLICIES
-- ==========================================
CREATE POLICY "Users can view own profile" ON public.users FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON public.users FOR UPDATE USING (auth.uid() = id);

-- ==========================================
-- VENDOR POLICIES
-- ==========================================
CREATE POLICY "Public can view vendors" ON public.vendors FOR SELECT USING (true);
CREATE POLICY "Vendors can update own data" ON public.vendors FOR UPDATE USING (auth.uid() = owner_id);

-- ==========================================
-- MENU POLICIES
-- ==========================================
CREATE POLICY "Public can view menus" ON public.menus FOR SELECT USING (true);
CREATE POLICY "Vendors can manage their menus" ON public.menus FOR ALL USING (
  EXISTS (SELECT 1 FROM public.vendors WHERE vendors.id = menus.vendor_id AND vendors.owner_id = auth.uid())
);

-- ==========================================
-- MENU ITEM POLICIES
-- ==========================================
CREATE POLICY "Public can view menu items" ON public.menu_items FOR SELECT USING (true);
CREATE POLICY "Vendors can manage menu items" ON public.menu_items FOR ALL USING (
  EXISTS (
    SELECT 1 FROM public.menus 
    JOIN public.vendors ON vendors.id = menus.vendor_id
    WHERE menus.id = menu_items.menu_id AND vendors.owner_id = auth.uid()
  )
);

-- ==========================================
-- ORDER POLICIES
-- ==========================================
CREATE POLICY "Users can view own orders" ON public.orders FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own orders" ON public.orders FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Vendors can view their orders" ON public.orders FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.vendors WHERE vendors.id = orders.vendor_id AND vendors.owner_id = auth.uid())
);
CREATE POLICY "Vendors can update their orders" ON public.orders FOR UPDATE USING (
  EXISTS (SELECT 1 FROM public.vendors WHERE vendors.id = orders.vendor_id AND vendors.owner_id = auth.uid())
);

-- ==========================================
-- ORDER ITEM POLICIES
-- ==========================================
CREATE POLICY "Users can insert own order items" ON public.order_items FOR INSERT WITH CHECK (
  EXISTS (
    SELECT 1
    FROM public.orders
    WHERE orders.id = order_items.order_id
      AND orders.user_id = auth.uid()
  )
);

CREATE POLICY "Users and vendors can view order items" ON public.order_items FOR SELECT USING (
  EXISTS (
    SELECT 1
    FROM public.orders
    WHERE orders.id = order_items.order_id
      AND (
        orders.user_id = auth.uid()
        OR EXISTS (
          SELECT 1
          FROM public.vendors
          WHERE vendors.id = orders.vendor_id AND vendors.owner_id = auth.uid()
        )
      )
  )
);

-- ==========================================
-- DELIVERY LOCATION POLICIES
-- ==========================================
CREATE POLICY "Vendors can upsert delivery locations" ON public.order_delivery_locations FOR ALL USING (
  EXISTS (
    SELECT 1 FROM public.orders
    JOIN public.vendors ON vendors.id = orders.vendor_id
    WHERE orders.id = order_delivery_locations.order_id AND vendors.owner_id = auth.uid()
  )
);

CREATE POLICY "Users can view delivery locations" ON public.order_delivery_locations FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM public.orders
    WHERE orders.id = order_delivery_locations.order_id AND orders.user_id = auth.uid()
  )
);

-- ==========================================
-- CAMPUS & DELIVERY ZONE POLICIES
-- ==========================================
CREATE POLICY "Public can view campus buildings" ON public.campus_buildings FOR SELECT USING (true);
CREATE POLICY "Public can view delivery zones" ON public.delivery_zones FOR SELECT USING (true);

-- ==========================================
-- CLASS SESSION POLICIES
-- ==========================================
CREATE POLICY "Users can manage own class sessions" ON public.class_sessions FOR ALL USING (auth.uid() = user_id);

-- ==========================================
-- CART POLICIES
-- ==========================================
CREATE POLICY "Users can view own cart" ON public.user_carts FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own cart" ON public.user_carts FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own cart" ON public.user_carts FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own cart" ON public.user_carts FOR DELETE USING (auth.uid() = user_id);

-- ==========================================
-- PROMOTION POLICIES
-- ==========================================
CREATE POLICY "Public can view active promotions" ON public.promotions FOR SELECT USING (
  is_active = true AND (starts_at IS NULL OR starts_at <= now()) AND (ends_at IS NULL OR ends_at >= now())
);

-- ==========================================
-- NOTIFICATION POLICIES
-- ==========================================
CREATE POLICY "Users can view own notifications" ON public.notifications FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can update own notifications" ON public.notifications FOR UPDATE USING (auth.uid() = user_id);

-- ==========================================
-- DEVICE TOKEN POLICIES
-- ==========================================
CREATE POLICY "Users can manage own device tokens" ON public.device_tokens FOR ALL USING (auth.uid() = user_id);

-- ==========================================
-- PROMOTION REDEMPTION POLICIES
-- ==========================================
CREATE POLICY "Users can view own promo redemptions" ON public.promotion_redemptions FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own promo redemptions" ON public.promotion_redemptions FOR INSERT WITH CHECK (auth.uid() = user_id);

-- ==========================================
-- MEDIA ITEM POLICIES
-- ==========================================
CREATE POLICY "Vendors can manage their media" ON public.media_items FOR ALL USING (
  EXISTS (SELECT 1 FROM public.vendors WHERE vendors.id = media_items.vendor_id AND vendors.owner_id = auth.uid())
);
CREATE POLICY "Public can view active media" ON public.media_items FOR SELECT USING (is_active = true);

-- ==========================================
-- WALLET & TRANSACTION POLICIES
-- ==========================================
CREATE POLICY "Users can view own wallet transactions" ON public.wallet_transactions FOR SELECT USING (auth.uid() = user_id);

-- ==========================================
-- REFERRAL POLICIES
-- ==========================================
CREATE POLICY "Users can view own referral codes" ON public.referral_codes FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can view referral redemptions" ON public.referral_redemptions FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM public.referral_codes
    WHERE referral_codes.id = referral_redemptions.referral_code_id AND referral_codes.user_id = auth.uid()
  )
);

-- ==========================================
-- LOYALTY POLICIES
-- ==========================================
CREATE POLICY "Users can view own loyalty account" ON public.loyalty_accounts FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can view own loyalty events" ON public.loyalty_events FOR SELECT USING (auth.uid() = user_id);

-- ==========================================
-- SUBSCRIPTION POLICIES
-- ==========================================
CREATE POLICY "Users can view own subscriptions" ON public.subscriptions FOR SELECT USING (auth.uid() = user_id);

-- ==========================================
-- VENDOR WATCH POLICIES
-- ==========================================
CREATE POLICY "Users can manage own vendor watches" ON public.vendor_watches FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Public can view vendor watches" ON public.vendor_watches FOR SELECT USING (true);

-- ==========================================
-- GROUP ORDER POLICIES
-- ==========================================
CREATE POLICY "Users can view group orders they are in" ON public.group_orders FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM public.group_order_members
    WHERE group_order_members.group_order_id = group_orders.id AND group_order_members.user_id = auth.uid()
  ) OR host_user_id = auth.uid()
);

-- ==========================================
-- REFUND REQUEST POLICIES
-- ==========================================
CREATE POLICY "Users can view own refund requests" ON public.refund_requests FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can create refund requests" ON public.refund_requests FOR INSERT WITH CHECK (auth.uid() = user_id);

-- ==========================================
-- CHAT & SUPPORT POLICIES
-- ==========================================
CREATE POLICY "Users can view their chat rooms" ON public.chat_rooms FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM public.chat_room_participants
    WHERE chat_room_participants.room_id = chat_rooms.id AND chat_room_participants.user_id = auth.uid()
  )
);

CREATE POLICY "Users can view messages in their rooms" ON public.chat_messages FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM public.chat_room_participants
    WHERE chat_room_participants.room_id = chat_messages.room_id AND chat_room_participants.user_id = auth.uid()
  )
);

CREATE POLICY "Users can insert messages in their rooms" ON public.chat_messages FOR INSERT WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.chat_room_participants
    WHERE chat_room_participants.room_id = chat_messages.room_id AND chat_room_participants.user_id = auth.uid()
  ) AND sender_type = 'user'
);

CREATE POLICY "Users can view own support tickets" ON public.support_tickets FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can create support tickets" ON public.support_tickets FOR INSERT WITH CHECK (auth.uid() = user_id);

-- ==========================================
-- ACCOUNT DELETION POLICIES
-- ==========================================
CREATE POLICY "Users can view own deletion request" ON public.user_deletion_requests FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can manage own deletion request" ON public.user_deletion_requests FOR ALL USING (auth.uid() = user_id);

-- ==========================================
-- ADMIN LOG POLICIES
-- ==========================================
-- Admin-only policies would be enforced at the backend level via RBAC checks
